# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 15:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopper', '0006_auto_20171221_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_wish_list',
            old_name='profile',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='user_order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='eshopper.Coupon'),
        ),
        migrations.AddField(
            model_name='user_order',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='eshopper.Product'),
        ),
    ]
