# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopper', '0007_auto_20171222_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together=set([]),
        ),
    ]
