# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshopper', '0008_auto_20171225_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
